from eelab import *
from eelab.data import alice_text
from eelab.core import ROOT
import zlib, bz2, lzma
from math import isqrt

META = dict(
    id="AM-218", title="Kolmogorov complexity: compression as a (computable) upper bound", level="H",
    tools="Real compressors (zlib, bz2, lzma) as upper bounds on description length, the counting argument for incompressible strings checked on random data, low-complexity strings that defeat compressors (digits of √2 generated by integer square roots, an LFSR sequence), normalised compression distance for clustering texts without any features",
    summary="Kolmogorov complexity — the length of the shortest program producing a string — is uncomputable, but compressors bound it from above. Test the "
            "counting argument, find strings whose true complexity is tiny yet no compressor notices, and use compression alone to cluster documents by kind.",
    problem="What is the information content of one specific string (not of a random source) — and can a computer measure it?",
    theory=r"""K(x) = length of the shortest program printing x; K is uncomputable (no algorithm returns it for all x), but any compressor C gives $K(x)\le|C(x)|+c$. Counting: fewer than $2^{n-k}$ programs are shorter than n − k bits, so at most a fraction $2^{-k+1}$ of n-bit strings can be compressed
by k bits — random data are incompressible. Conversely √2's digits or an LFSR output have K of a few hundred bits (the generating program) though they look random to statistical compressors. Normalised compression distance
$\mathrm{NCD}(x,y)=\frac{C(xy)-\min(C(x),C(y))}{\max(C(x),C(y))}$ approximates the (uncomputable) information distance; similar objects compress well together.""",
    method="""Random bytes: 1000 strings of 1 kB through three compressors. √2: 20 000 decimal digits from isqrt(2·10^{2n}); LFSR: 160 000-bit m-sequence of degree 17 packed into bytes; their generating programs are the source strings shown in this file. NCD with lzma between 16 chunks of 6 kB:
4 from 'Alice', 4 from this repository's Python source, 4 of √2 digits, 4 of letters drawn i.i.d. with English frequencies. Nearest-neighbour agreement with the true category.""",
    data="Project Gutenberg eBook #11; the repository's own source code.",
)

PROG_SQRT2 = "from math import isqrt; s = str(isqrt(2 * 10 ** 40000))[:20000]"
PROG_LFSR = "s=1;o=[]\nfor _ in range(160000):\n b=((s>>16)^(s>>13))&1; o.append(b); s=((s<<1)|b)&0x1FFFF"


def comp(b):
    return {"zlib": len(zlib.compress(b, 9)), "bz2": len(bz2.compress(b, 9)), "lzma": len(lzma.compress(b, preset=9 | lzma.PRESET_EXTREME))}


def run(p):
    import sys
    sys.set_int_max_str_digits(0)                                  # √2 to 20 000 digits needs big-int ↔ str conversion
    r = p.rng; worst = 0; best_ratio = 0.0
    for _ in range(1000):
        b = bytes(r.integers(0, 256, 1024, dtype=np.uint8)); c = comp(b); best_ratio = max(best_ratio, 1024 / min(c.values())); worst += min(c.values()) < 1024
    p.compare("Counting argument: random 1 kB strings that any of three compressors shortened (of 1000)", 0, worst, "", kind="abs")
    ns = {}; exec(PROG_SQRT2, {"isqrt": isqrt}, ns); s2 = ns["s"].encode()
    ok = s2[:10] == b"1414213562"
    p.compare("Program reproduces √2 = 1.414213562… (1 = yes)", 1, int(ok), "", kind="abs")
    c = comp(s2); bits_digit = 8 * min(c.values()) / len(s2)
    p.compare("20 000 digits of √2: best compressor needs ≈ log₂10 = 3.32 bits per digit — it sees no structure", np.log2(10), bits_digit, "bit", tol=5)
    p.metric("… while a complete program for them is", len(PROG_SQRT2), "bytes", f"vs {min(c.values())} bytes compressed: K(x) ≪ what any compressor finds")
    ns = {}; exec(PROG_LFSR, {}, ns); bits = np.array(ns["o"], np.uint8); lb = np.packbits(bits).tobytes()
    cl = comp(lb)
    p.compare("m-sequence (degree 17), 20 kB: best compression ratio stays ≈ 1 (> 0.9; 1 = yes)", 1, int(min(cl.values()) / len(lb) > 0.9), "", kind="abs")
    period_ok = np.array_equal(bits[:1000], bits[131071:132071])
    p.compare("… although it is periodic with period 2¹⁷ − 1 and fully described by a 3-line program (period check; 1 = yes)", 1, int(period_ok), "", kind="abs")
    p.metric("LFSR stream: compressed size (best of three) / program size", f"{min(cl.values())} / {len(PROG_LFSR)} bytes")
    text = alice_text().encode()
    src = b"".join(open(f, "rb").read() for f in sorted((ROOT / "eelab").glob("*.py")))
    freq = np.bincount(np.frombuffer(text, np.uint8), minlength=256) / len(text)
    fake = bytes(r.choice(256, 60000, p=freq).astype(np.uint8))
    L = 6000; chunks = []; labels = []
    for name, data, off in (("Alice", text, 20000), ("code", src, 5000), ("√2", s2 * 2, 0), ("iid letters", fake, 0)):
        for i in range(4):
            chunks.append(data[off + i * L * 2: off + i * L * 2 + L]); labels.append(name)
    C = lambda b: len(lzma.compress(b, preset=9))
    cs = [C(x) for x in chunks]; n = len(chunks); D = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i != j:
                D[i, j] = (C(chunks[i] + chunks[j]) - min(cs[i], cs[j])) / max(cs[i], cs[j])
    np.fill_diagonal(D, np.inf); nn = D.argmin(1)
    acc = np.mean([labels[i] == labels[nn[i]] for i in range(n)])
    p.compare("NCD nearest neighbour belongs to the same kind of document (16 chunks, 4 kinds)", 1.0, float(acc), "", tol=1e-9)
    within = np.mean([D[i, j] for i in range(n) for j in range(n) if i != j and labels[i] == labels[j]]); between = np.mean([D[i, j] for i in range(n) for j in range(n) if labels[i] != labels[j]])
    p.metric("Mean NCD within kind / between kinds", f"{within:.2f} / {between:.2f}")
    p.metric("Compressed bits per byte (lzma): Alice / code / √2 digits / i.i.d. letters", " / ".join(f"{8 * np.mean([cs[i] for i in range(n) if labels[i] == k]) / L:.2f}" for k in ("Alice", "code", "√2", "iid letters")))
    fig, ax = p.fig(1, 2, w=11, h=4.6)
    Dp = D.copy(); np.fill_diagonal(Dp, 0); im = ax[0].imshow(Dp, cmap="viridis"); fig.colorbar(im, ax=ax[0], label="NCD")
    ax[0].set_xticks(range(n)); ax[0].set_xticklabels(labels, rotation=90, fontsize=7); ax[0].set_yticks(range(n)); ax[0].set_yticklabels(labels, fontsize=7); ax[0].grid(False)
    ax[0].set_title("Normalised compression distance", loc="left", fontsize=10)
    names = ["random\nbytes", "√2\ndigits", "LFSR\nbits", "Alice", "Python\ncode"]
    comp_bits = [8.0 * 1024 / 1024 * 1.0, bits_digit / np.log2(10) * 8 * np.log2(10) / 8 * 8 / 8, 8 * min(cl.values()) / len(lb), 8 * min(comp(text).values()) / len(text), 8 * min(comp(src).values()) / len(src)]
    comp_bits[1] = 8 * min(c.values()) / len(s2)
    ax[1].bar(names, comp_bits, color=[COLORS[7], C_PRED, C_PRED, C_MEAS, C_MEAS])
    style_axes(ax[1], "", "compressed bits per byte (best of 3)", "Compressors bound K(x) from above — sometimes badly", legend=False)
    p.save(fig, "kolmogorov", "NCD matrix of 16 document chunks, and how much each kind of data compresses.")
    p.discuss(f"""Compressors are the practical handle on Kolmogorov complexity, and the experiments show both sides of the bound K(x) ≤ |C(x)| + c. The counting
argument holds: none of 1000 random kilobyte strings could be shortened by any of three compressors. But the bound can be very loose: 20 000
digits of √2 compress only to {bits_digit:.2f} bits per digit — indistinguishable from random — while the {len(PROG_SQRT2)}-byte program at the top of this file produces
them exactly; an m-sequence of 160 000 bits is likewise incompressible to all three tools although a three-line loop generates it. Statistical
compressors find only the regularities they model. Used relatively, however, compression is a remarkably general similarity measure: with no
features or training, the normalised compression distance put every one of 16 text chunks next to another of its own kind (prose, source code,
digits, letter salad) — the idea behind compression-based classification of languages, malware and DNA.""")
# tol-convention: relative tolerances are in percent
